#!/usr/bin/env zsh

#############
#  Aliases  #
#############

# List declared aliases, functions, paths
alias aliases="alias | sed 's/=.*//'"
alias functions="declare -f | grep '^[a-z].* ()' | sed 's/{$//'"
alias paths='echo -e ${PATH//:/\\n}'

# Has package
alias has="curl -sL https://git.io/_has | bash -s "

# Update
alias update='sudo softwareupdate -i -a; brew update; brew upgrade; brew cleanup;'

# Set ls color
alias ls="ls --color=auto"

# Nvim
alias vi="nvim"
alias vim="nvim"

# Edit configs
alias zenv="vi $HOME/.zshenv"
alias zpro="vi $ZDOTDIR/.zprofile"
alias zrc="vi $ZDOTDIR/.zshrc"
alias vrc="vi ~/.vimrc"
alias nrc="vi $XDG_CONFIG_HOME/nvim/init.lua"
alias wrc="vi $XDG_CONFIG_HOME/wezterm/wezterm.lua"

# Git
alias gg='git grep -E'

# Zplug
alias zpui="zplug update && zplug install"

# Stow
alias stowdir="stow --no-folding --dotfiles --verbose=2 -R -t ~ "

# SSH
alias rotatekeys="source $HOME/ssh-key-manager.sh && rotate_keys"
alias displaykeys="source $HOME/ssh-key-manager.sh && display_public_keys"

# Arduino
alias ard="arduino-cli"
alias ardc="arduino-cloud-cli"

# -------------------------------------------------------------------------------------------------
# -*- mode: zsh; sh-indentation: 2; indent-tabs-mode: nil; sh-basic-offset: 2; -*-
# vim: ft=zsh sw=2 ts=2 et
# -------------------------------------------------------------------------------------------------
