#!/usr/bin/env zsh

# Available completion styles: gremlin, ohmy, prez, zshzoo
zstyle ':plugin:ez-compinit' 'compstyle' 'zshzoo'

# Friendly repo names
zstyle ':antidote:bundle' use-friendly-names 'yes'

# Alias Finder
zstyle ':alias-finder' longer true
zstyle ':alias-finder' exact false
zstyle ':alias-finder' cheaper true
zstyle ':alias-finder' autoload true

# Ssh-agent
# Set the environment cache file
zstyle ':ssh-agent' env-cache "${SSH_CACHE_DIR:-$HOME/.cache/ssh}/environment-${SHORT_HOST:-default}"
# Set the agent lifetime
zstyle ':ssh-agent' lifetime "12h"
# Set specific identities to load not in .ssh/config
# zstyle ':ssh-agent' identities dhgit esstudy github ldap porky yakko

# -------------------------------------------------------------------------------------------------
# -*- mode: zsh; sh-indentation: 2; indent-tabs-mode: nil; sh-basic-offset: 2; -*-
# vim: ft=zsh sw=2 ts=2 et
# -------------------------------------------------------------------------------------------------
