#!/usr/bin/env zsh

# ========================= Zplug Setup ========================================
if [[ ! -d ~/.zplug ]]; then
  git clone https://github.com/zplug/zplug ~/.zplug
  source ~/.zplug/init.zsh && zplug update --self
fi

source ~/.zplug/init.zsh

zplug 'zplug/zplug', hook-build:'zplug --self-manage'

# ========================= Plugins Setup ======================================

# ---- ZSH Syntax Theme -------
[[ -r "$ZSH_SYNTAX_THEME" ]] && source "$ZSH_SYNTAX_THEME"

# --- Package Managers --------
zplug "plugins/asdf", from:oh-my-zsh

# ---- Language Plugins -------
# zplug "lukechilds/zsh-nvm"
# zplug "mattberther/zsh-pyenv"
# zplug "orbstack/orbstack", defer:1
# zplug "DhavalKapil/luaver"
# zplug "wushenrong/zsh-plenv"

# ---- Supercrab Tree ----------
zplug "supercrabtree/k"

# ---- FZF Setup ---------------
zplug "junegunn/fzf", use:"shell/*.zsh", hook-build:"./install --all"

# ---- Diff So Fancy ---------
zplug "so-fancy/diff-so-fancy", as:command, use:"diff-so-fancy"

# ---- Oh-My-Zsh Plugins ------
zplug "plugins/git", from:oh-my-zsh
zplug "plugins/npm", from:oh-my-zsh
zplug "plugins/sudo", from:oh-my-zsh
zplug "plugins/ssh-agent", from:oh-my-zsh
zplug "plugins/common-aliases", from:oh-my-zsh

# ---- Zsh Users Plugins -------
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug "zsh-users/zsh-history-substring-search", defer:2

# ========================= Zplug Install and Load =============================
if ! zplug check --verbose; then
  echo; zplug install
fi

zplug load

# ========================= General Settings ===================================
# -- History settings
ZSTATE="$XDG_STATE_HOME/zsh"

if [[ ! -d $ZSTATE ]]; then
    echo "Creating directory: $ZSTATE"
    mkdir -p "$ZSTATE" || { echo "Failed to create history dir: $ZSTATE" >&2; return 1; }
fi

HISTFILE="$ZSTATE/zsh_history"
HISTSIZE=1000000
SAVEHIST="$HISTSIZE"

setopt SHARE_HISTORY          # Share history across all sessions
setopt EXTENDED_HISTORY       # Record command execution time
setopt HIST_VERIFY            # Don't execute immediately upon history expansion
setopt HIST_REDUCE_BLANKS     # Remove unnecessary blanks
setopt HIST_IGNORE_SPACE      # Ignore commands with leading spaces
setopt HIST_IGNORE_DUPS       # Ignore duplicate commands
setopt HIST_IGNORE_ALL_DUPS   # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS      # Do not display old duplicates in history search
setopt HIST_SAVE_NO_DUPS      # Do not save duplicate commands in history
setopt HIST_EXPIRE_DUPS_FIRST # Expire a duplicate event first when trimming history.

# ========================= Key Bindings =======================================

bindkey -e

# -- History substring search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# ========================= Visual Settings ====================================

# -- Set dircolors and completion colors
eval "$(dircolors --sh $ZDOTDIR/colors/gruvbox.default.dircolors)"
IFS=: read -rA ls_colors_array <<<"$LS_COLORS"
zstyle ':completion:*' list-colors "${ls_colors_array[@]}"

# ========================= Set Machine Type ===================================
fullname=$(hostname -f 2>/dev/null || hostname)
case $fullname in
*dreamhost.com) ;&
*newdream.net)
  machine_type="ndn"
  ;;
esac

# ========================= Source The Things ==================================

# -- Aliases and Functions
[[ -r "$ZDOTDIR/.aliases" ]] && source "$ZDOTDIR/.aliases"
[[ -r "$ZDOTDIR/.functions" ]] && source "$ZDOTDIR/.functions"
[[ -r "$ZDOTDIR/.aliases.$machine_type" ]] && source "$ZDOTDIR/.aliases.$machine_type"
[[ -r "$ZDOTDIR/.functions.$machine_type" ]] && source "$ZDOTDIR/.functions.$machine_type"

# -- FZF
[[ -r ~/.fzf.zsh ]] && source ~/.fzf.zsh

# -- Direnv
[[ -r "${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/zshrc" ]] && source "${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/zshrc"

# -- Wezterm
[[ -x "${XDG_CONFIG_HOME:-$HOME/.config}/wezterm/wezterm.sh" ]] && source "${XDG_CONFIG_HOME:-$HOME/.config}/wezterm/wezterm.sh"

# -- Starship
eval "$(starship init zsh)"

# -- thefuck
eval "$(thefuck --alias)"

# -- Mise
# eval "$(mise activate zsh)"

# -------------------------------------------------------------------------------------------------
# -*- mode: zsh; sh-indentation: 2; indent-tabs-mode: nil; sh-basic-offset: 2; -*-
# vim: ft=zsh sw=2 ts=2 et
# -------------------------------------------------------------------------------------------------
