#!/usr/bin/env zsh

# ========================= Zplug Setup ========================================
if [[ ! -d ~/.zplug ]]; then
  git clone https://github.com/zplug/zplug ~/.zplug
  source ~/.zplug/init.zsh && zplug update --self
fi

source ~/.zplug/init.zsh

zplug 'zplug/zplug', hook-build:'zplug --self-manage'

# ========================= Plugins Setup ======================================

# ZSH Syntax Theme
[[ -r "$ZSH_SYNTAX_THEME" ]] && source "$ZSH_SYNTAX_THEME"

# FZF Setup
zplug "junegunn/fzf", use:"shell/*.zsh", hook-build:"./install --all"

# Diff So Fancy
zplug "so-fancy/diff-so-fancy", as:command, use:"diff-so-fancy"

# Custom Plugins
zplug "$ZDOTDIR/plugins/bun", from:local
zplug "$ZDOTDIR/plugins/npm", from:local
zplug "$ZDOTDIR/plugins/git", from:local
zplug "$ZDOTDIR/plugins/rust", from:local
zplug "$ZDOTDIR/plugins/starship", from:local

zplug "$ZDOTDIR/plugins/history", from:local
zplug "$ZDOTDIR/plugins/ssh-agent", from:local
zplug "$ZDOTDIR/plugins/completion", from:local
zplug "$ZDOTDIR/plugins/common-aliases", from:local
zplug "$ZDOTDIR/plugins/alias-finder", from:local
# zplug "$ZDOTDIR/plugins/asdf", from:local

# Rust Replacements
# LS CD GREP CAT FIND SED PS DU MAN DIFF
# EZA ZOXIDE RIPGREP BAT FD SD PROCS DUST TEALDEER DELTA
zplug "z-shell/zsh-eza"
zplug "$ZDOTDIR/plugins/eza", from:local

# Zsh Users Plugins
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug "zsh-users/zsh-history-substring-search", defer:2

if ! zplug check --verbose; then
  echo; zplug install
fi

zplug load

# ========================= Key Bindings =======================================

# Emacs
bindkey -e

# History substring search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# ========================= Visual Settings ====================================

# Set dircolors and completion colors
if (( $+commands[dircolors] )); then
  eval "$(dircolors --sh $ZDOTDIR/colors/gruvbox.default.dircolors)"
elif (( $+commands[gdircolors] )); then
  eval "$(gdircolors --sh $ZDOTDIR/colors/gruvbox.default.dircolors)"
fi

# ========================= Completion Settings ================================

# zstyle ':completion:*' auto-description 'specify: %d'
# zstyle ':completion:*' completer _expand _complete _correct _approximate
# zstyle ':completion:*' format 'Completing %d'
# zstyle ':completion:*' group-name ''
# zstyle ':completion:*' menu select=2
# zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
# zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
# zstyle ':completion:*' menu select=long
# zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
# zstyle ':completion:*' use-compctl false
# zstyle ':completion:*' verbose yes
#
# zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
# zstyle ':completion:*:kill:*' command 'ps -u "$USER" -o pid,%cpu,tty,cputime,cmd'
#
# # Completion colors
# [[ -z "$LS_COLORS" ]] || zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"

# ========================= Set Machine Type ===================================
fullname=$(hostname -f 2>/dev/null || hostname)
case $fullname in
*dreamhost.com) ;&
*newdream.net)
  machine_type="ndn"
  ;;
esac

# ========================= Source The Things ==================================

# Aliases and Functions
[[ -r "$ZDOTDIR/.aliases" ]] && source "$ZDOTDIR/.aliases"
[[ -r "$ZDOTDIR/.functions" ]] && source "$ZDOTDIR/.functions"
[[ -r "$ZDOTDIR/.aliases.$machine_type" ]] && source "$ZDOTDIR/.aliases.$machine_type"
[[ -r "$ZDOTDIR/.functions.$machine_type" ]] && source "$ZDOTDIR/.functions.$machine_type"

# -- Mise
eval "$(mise activate zsh)"

# -- Starship
eval "$(starship init zsh)"

# -- thefuck
eval "$(thefuck --alias)"

# -- FZF
[[ -r ~/.fzf.zsh ]] && source ~/.fzf.zsh

# -- Wezterm
[[ -x "${XDG_CONFIG_HOME:-$HOME/.config}/wezterm/wezterm.sh" ]] && source "${XDG_CONFIG_HOME:-$HOME/.config}/wezterm/wezterm.sh"

# -- Direnv
[[ -r "${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/zshrc" ]] && source "${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/zshrc"

# -------------------------------------------------------------------------------------------------
# -*- mode: zsh; sh-indentation: 2; indent-tabs-mode: nil; sh-basic-offset: 2; -*-
# vim: ft=zsh sw=2 ts=2 et
# -------------------------------------------------------------------------------------------------
