#!/usr/bin/env zsh

zstyle ':antidote:bundle' use-friendly-names 'yes'

zstyle ':alias-finder' longer true
zstyle ':alias-finder' exact false
zstyle ':alias-finder' cheaper true
zstyle ':alias-finder' autoload true

# -------------------------------------------------------------------------------------------------
# -*- mode: zsh; sh-indentation: 2; indent-tabs-mode: nil; sh-basic-offset: 2; -*-
# vim: ft=zsh sw=2 ts=2 et
# -------------------------------------------------------------------------------------------------
