#!/usr/bin/env zsh

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export TERM='xterm-256color'
export EDITOR='nvim'
export VISUAL="$EDITOR"
export PAGER='less'

if [[ $(uname) == 'Darwin' ]]; then
  cores="$(sysctl -n hw.logicalcpu)"
elif [[ $(uname) == 'Linux' ]]; then
  cores="$(nproc)"
fi
export MACHINE_CORES="${cores:-4}"

export ENVDIR="$HOME/.config/env.d"
if [[ -d "$ENVDIR" ]]; then
  for env_file in "$ENVDIR"/*.conf; do
    [[ -r "$env_file" ]] && source "$env_file"
  done
fi

if command -v fc-cache &>/dev/null && [[ -d "$XDG_DATA_HOME/fonts" ]]; then
  fc-cache -f "$XDG_DATA_HOME/fonts"
fi

# Added by OrbStack: command-line tools and integration
# This won't be added again if you remove it.
source ~/.orbstack/shell/init.zsh 2>/dev/null || :

# -------------------------------------------------------------------------------------------------
# -*- mode: zsh; sh-indentation: 2; indent-tabs-mode: nil; sh-basic-offset: 2; -*-
# vim: ft=zsh sw=2 ts=2 et
# -------------------------------------------------------------------------------------------------
