#!/usr/bin/env zsh

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export TERM='xterm-256color'
export EDITOR='nvim'
export VISUAL="$EDITOR"
export PAGER='less'

export OSTYPE="$(uname)"

if [[ "$OSTYPE" == darwin* ]]; then
  cores="$(sysctl -n hw.logicalcpu)"
elif [[ "$OSTYPE" == linux* ]]; then
  cores="$(nproc)"
fi
export MACHINE_CORES="${cores:-4}"

export ENV_DIR="$HOME/.config/env.d"
if [[ -d "$ENV_DIR" ]]; then
  for conf in "$ENV_DIR"/*.conf; do
    [[ -r "$conf" ]] && source "$conf"
  done
fi

if [[ ! -z "$ENV_DIRS" ]]; then
  for dir in ${(s/:/)ENV_DIRS}; do
    if [[ ! -d "$dir" ]]; then
      mkdir -p "$dir"
    fi
  done
  unset ENV_DIRS
fi

# Added by OrbStack: command-line tools and integration
# This won't be added again if you remove it.
source ~/.orbstack/shell/init.zsh 2>/dev/null || :

# -------------------------------------------------------------------------------------------------
# -*- mode: zsh; sh-indentation: 2; indent-tabs-mode: nil; sh-basic-offset: 2; -*-
# vim: ft=zsh sw=2 ts=2 et
# -------------------------------------------------------------------------------------------------
