#!/usr/bin/env zsh

#############
#  Aliases  #
#############

# List declared aliases, functions, paths
alias aliases='alias | sed "s/=.*//"'
alias functions='declare -f | grep "^[a-z].* ()" | sed "s/{$//"'
alias paths='echo -e ${PATH//:/\\n}'

# Has package
alias has='curl -sL https://git.io/_has | bash -s '

# Update
alias update='sudo softwareupdate -i -a; brew update; brew upgrade; brew cleanup;'

# Easy ls and set ls color
alias l='ls -lah'
alias ls='ls --color=auto'

# CD Shortcuts
alias dh='cd $DHSPACE'
alias dots='cd $DOTFILES'

# Edit configs
alias vrc='${=EDITOR} ~/.vimrc'
alias nrc='${=EDITOR} $XDG_CONFIG_HOME/nvim/init.lua'
alias wrc='${=EDITOR} $XDG_CONFIG_HOME/wezterm/wezterm.lua'
alias zenv='${=EDITOR} $HOME/.zshenv'
alias zrc='${=EDITOR} ${ZDOTDIR:-$HOME}/.zshrc'
alias zpro='${=EDITOR} ${ZDOTDIR:-$HOME}/.zprofile'

# Edit aliases
alias aliasrc='${=EDITOR} ${ZDOTDIR:-$HOME}/.aliases'

# LDE
alias ldelog='lde logs -ftall '

# Nvim
alias vi='${=EDITOR}'
# alias vim='nvim'

# Git
alias gg='git grep -E'

# Zplug
alias zpui='zplug update && zplug install'

# Stow
alias stowdir='stow --no-folding --dotfiles --verbose=1 -R -t ~ '

# ASDF
alias asdfplugs='cut -d' ' -f1 $ASDF_DEFAULT_TOOL_VERSIONS_FILENAME|xargs -i asdf plugin add  {}'

# SSH
alias rotatekeys='source $HOME/ssh-key-manager.sh && rotate_keys'
alias displaykeys='source $HOME/ssh-key-manager.sh && display_public_keys'

# Arduino
alias ard='arduino-cli'
alias ardc='arduino-cloud-cli'

# -------------------------------------------------------------------------------------------------
# -*- mode: zsh; sh-indentation: 2; indent-tabs-mode: nil; sh-basic-offset: 2; -*-
# vim: ft=zsh sw=2 ts=2 et
# -------------------------------------------------------------------------------------------------
