#!/usr/bin/env zsh

# This is only the essentials, use .zprofile for the rest. Also, Mac is dumb and sources /etc/zprofile after this file
# so you cannot set paths reliably here.

export ZDOTDIR="$HOME/.config/zsh"
if [[ ! -d "$ZDOTDIR" ]]; then
    mkdir -p "$ZDOTDIR" || { echo "Failed to create dir: $ZDOTDIR" >&2; return 1; }
fi

# -------------------------------------------------------------------------------------------------
# -*- mode: zsh; sh-indentation: 2; indent-tabs-mode: nil; sh-basic-offset: 2; -*-
# vim: ft=zsh sw=2 ts=2 et
# -------------------------------------------------------------------------------------------------
